module.exports = {
  OAuthTokens: require('./oAuthTokens'),
  Users: require('./users'),
  CodeCounties: require('./codeCounties'),
  Categories: require('./categories'),
  Faqs: require('./faqs'),
  Services: require('./services'),
  Providers: require('./providers'),
  TypesServices: require('./typesServices'),
  Payments: require('./payments'),
  Orders: require('./orders'),
  Transactions: require('./transactions'),
  Favorites: require('./favorites'),
  FavoritesCategories: require('./favoritesCategories'),
  Tickets: require('./tickets'),
  TicketsMessages: require('./ticketsMessages'),
  Refills: require('./refills'),
  Points: require('./points'),
  RequestChildPanels: require('./requestChildPanels'),
  Notifications: require('./notifications'),
};
